version: '3'
services:
  database:
    image: "postgres:15" # use latest official postgres version
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: "redis:7"
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  database-data: # named volumes can be managed easier using docker-compose
