name: c9
services:
  cloud-nine-mock-ase:
    hostname: cloud-nine-wallet
    image: rafiki-mock-ase
    build:
      context: ../..
      dockerfile: ./localenv/mock-account-servicing-entity/Dockerfile
    restart: always
    networks:
      - rafiki
    ports:
      - '3030:80'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      LOG_LEVEL: debug
      PORT: 80
      SEED_FILE_LOCATION: /workspace/seed.yml
      KEY_FILE: /workspace/private-key.pem
      OPEN_PAYMENTS_URL: ${CLOUD_NINE_OPEN_PAYMENTS_URL:-https://cloud-nine-wallet-backend}
      AUTH_SERVER_DOMAIN: ${CLOUD_NINE_AUTH_SERVER_DOMAIN:-http://localhost:3006}
      TESTNET_AUTOPEER_URL: ${TESTNET_AUTOPEER_URL}
    volumes:
      - ../cloud-nine-wallet/seed.yml:/workspace/seed.yml
      - ../cloud-nine-wallet/private-key.pem:/workspace/private-key.pem
    depends_on:
      - cloud-nine-backend
  cloud-nine-backend:
    hostname: cloud-nine-wallet-backend
    image: rafiki-backend
    build:
      context: ../..
      dockerfile: ./packages/backend/Dockerfile
    restart: always
    privileged: true
    ports:
      - '3000:80'
      - '3001:3001'
      - '3002:3002'
    networks:
      - rafiki
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      TRUST_PROXY: ${TRUST_PROXY}
      LOG_LEVEL: debug
      ADMIN_PORT: 3001
      CONNECTOR_PORT: 3002
      OPEN_PAYMENTS_PORT: 80
      DATABASE_URL: postgresql://cloud_nine_wallet_backend:cloud_nine_wallet_backend@shared-database/cloud_nine_wallet_backend
      USE_TIGERBEETLE: ${USE_TIGERBEETLE-false}
      TIGERBEETLE_CLUSTER_ID: ${TIGERBEETLE_CLUSTER_ID-0}
      TIGERBEETLE_REPLICA_ADDRESSES: ${TIGERBEETLE_REPLICA_ADDRESSES-''}
      AUTH_SERVER_GRANT_URL: ${CLOUD_NINE_AUTH_SERVER_DOMAIN:-http://cloud-nine-wallet-auth:3006}
      AUTH_SERVER_INTROSPECTION_URL: http://cloud-nine-wallet-auth:3007
      ILP_ADDRESS: ${ILP_ADDRESS:-test.cloud-nine-wallet}
      STREAM_SECRET: BjPXtnd00G2mRQwP/8ZpwyZASOch5sUXT5o0iR5b5wU=
      OPEN_PAYMENTS_URL: ${CLOUD_NINE_OPEN_PAYMENTS_URL:-http://cloud-nine-wallet-backend}
      WEBHOOK_URL: http://cloud-nine-wallet/webhooks
      EXCHANGE_RATES_URL: http://cloud-nine-wallet/rates
      REDIS_URL: redis://shared-redis:6379/0
      WALLET_ADDRESS_URL: ${CLOUD_NINE_WALLET_ADDRESS_URL:-https://cloud-nine-wallet-backend/.well-known/pay}
      ILP_CONNECTOR_ADDRESS: ${CLOUD_NINE_CONNECTOR_URL}
    depends_on:
      - shared-database
      - shared-redis
  cloud-nine-auth:
    hostname: cloud-nine-wallet-auth
    image: rafiki-auth
    build:
      context: ../..
      dockerfile: ./packages/auth/Dockerfile
    restart: always
    networks:
      - rafiki
    ports:
      - '3003:3003'
      - '3006:3006'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      TRUST_PROXY: ${TRUST_PROXY}
      AUTH_DATABASE_URL: postgresql://cloud_nine_wallet_auth:cloud_nine_wallet_auth@shared-database/cloud_nine_wallet_auth
      AUTH_SERVER_DOMAIN: ${CLOUD_NINE_AUTH_SERVER_DOMAIN:-http://localhost:3006}
    depends_on:
      - shared-database
  shared-database:
    image: 'postgres:15' # use latest official postgres version
    restart: unless-stopped
    networks:
      - rafiki
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ../cloud-nine-wallet/dbinit.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
  shared-redis:
    image: 'redis:7'
    restart: unless-stopped
    networks:
      - rafiki
  cloud-nine-admin:
    hostname: cloud-nine-wallet-admin
    image: rafiki-frontend
    build:
      context: ../..
      dockerfile: ./packages/frontend/Dockerfile
    restart: always
    networks:
      - rafiki
    ports:
      - '3010:3010'
    environment:
      PORT: 3010
      GRAPHQL_URL: http://cloud-nine-wallet-backend:3001/graphql
      OPEN_PAYMENTS_URL: https://cloud-nine-wallet-backend/
    depends_on:
      - cloud-nine-backend

volumes:
  database-data: # named volumes can be managed easier using docker-compose

networks:
  rafiki:
    external: true
