name: hl
services:
  happy-life-mock-ase:
    hostname: happy-life-bank
    image: rafiki-mock-ase
    pull_policy: never
    restart: always
    networks:
      - rafiki
    ports:
      - '3031:80'
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      PORT: 80
      SEED_FILE_LOCATION: /workspace/seed.yml
      KEY_FILE: /workspace/private-key.pem
      OPEN_PAYMENTS_URL: ${HAPPY_LIFE_BANK_OPEN_PAYMENTS_URL:-https://happy-life-bank-backend}
    volumes:
      - ../happy-life-bank/seed.yml:/workspace/seed.yml
      - ../happy-life-bank/private-key.pem:/workspace/private-key.pem
    depends_on:
      - cloud-nine-mock-ase
      - happy-life-backend
  happy-life-backend:
    hostname: happy-life-bank-backend
    image: rafiki-backend
    pull_policy: never
    restart: always
    privileged: true
    ports:
      - "4000:80"
      - "4001:3001"
    networks:
      - rafiki
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      ADMIN_PORT: 3001
      CONNECTOR_PORT: 3002
      OPEN_PAYMENTS_PORT: 80
      DATABASE_URL: postgresql://happy_life_bank_backend:happy_life_bank_backend@shared-database/happy_life_bank_backend
      USE_TIGERBEETLE: ${USE_TIGERBEETLE-false}
      TIGERBEETLE_CLUSTER_ID: ${TIGERBEETLE_CLUSTER_ID-0}
      TIGERBEETLE_REPLICA_ADDRESSES: ${TIGERBEETLE_REPLICA_ADDRESSES-''}
      AUTH_SERVER_GRANT_URL: ${HAPPY_LIFE_BANK_AUTH_SERVER_DOMAIN:-http://happy-life-bank-auth:3006}
      AUTH_SERVER_INTROSPECTION_URL: http://happy-life-bank-auth:3007
      ILP_ADDRESS: test.happy-life-bank
      STREAM_SECRET: BjPXtnd00G2mRQwP/8ZpwyZASOch5sUXT5o0iR5b5wU=
      WEBHOOK_URL: http://happy-life-bank/webhooks
      OPEN_PAYMENTS_URL: ${HAPPY_LIFE_BANK_OPEN_PAYMENTS_URL:-http://happy-life-bank-backend}
      EXCHANGE_RATES_URL: http://happy-life-bank/rates
      REDIS_URL: redis://shared-redis:6379/1
      WALLET_ADDRESS_URL: ${HAPPY_LIFE_BANK_WALLET_ADDRESS_URL:-https://happy-life-bank-backend/.well-known/pay}
    depends_on:
      - cloud-nine-backend
  happy-life-auth:
    hostname: happy-life-bank-auth
    image: rafiki-auth
    pull_policy: never
    restart: always
    networks:
      - rafiki
    ports:
      - '4003:3003'
      - '4006:3006'
    environment:
      NODE_ENV: development
      AUTH_DATABASE_URL: postgresql://happy_life_bank_auth:happy_life_bank_auth@shared-database/happy_life_bank_auth
      AUTH_SERVER_DOMAIN: ${HAPPY_LIFE_BANK_AUTH_SERVER_DOMAIN:-http://localhost:4006}
    depends_on:
      - cloud-nine-auth
  happy-life-admin:
    hostname: happy-life-bank-admin
    image: rafiki-frontend
    pull_policy: never
    restart: always
    networks:
      - rafiki
    ports:
      - '4010:4010'
    environment:
      PORT: 4010
      GRAPHQL_URL: http://happy-life-bank-backend:3001/graphql
      OPEN_PAYMENTS_URL: https://happy-life-bank-backend/
    depends_on:
      - cloud-nine-admin
      - happy-life-backend

networks:
  rafiki:
    external: true
