name: Publish Postman API version (main)

on:
  push:
    branches:
      - main
    paths:
        - 'postman/**'
        - '.postman/**'

jobs:
  postman-publish-main:
    uses: ./.github/workflows/postman-publish.yml 
    with:
      api-version: 'main'
      release-notes: "APIs corresponding to Rafiki main branch"
      branch: 'main'
    secrets: inherit